export const products = [
  {
    id: 1,
    boutique: "Moda Eskişehir",
    city: "Eskişehir",
    district: "Merkez",
    name: "Siyah Oversize Gömlek",
    category: "shirt",
    color: "black",
    size: "oversize",
    deliveryType: "courier",
    deliveryTime: 90,
    price: 899,
    distance: "1.8 km",
    image: "👔",
  },
  {
    id: 2,
    boutique: "Trend Butik",
    city: "Eskişehir",
    district: "Merkez",
    name: "Kırmızı Elbise",
    category: "dress",
    color: "red",
    size: "M",
    deliveryType: "pickup",
    deliveryTime: 30,
    price: 1200,
    distance: "900 m",
    image: "👗",
  },
  {
    id: 3,
    boutique: "Street Wear House",
    city: "Eskişehir",
    district: "Merkez",
    name: "Siyah 3XL Tişört",
    category: "t-shirt",
    color: "black",
    size: "3XL",
    deliveryType: "courier",
    deliveryTime: 120,
    price: 650,
    distance: "2.4 km",
    image: "👕",
  },
];